### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by kneekey23** [slashmo/swift-app-store-receipt-validation#2]
Hi I would love to use this package but it looks like you haven't published a version of it since it's moved repos. Anyway you can publish the current version so I can take advantage of it in SPM? Gives me a version error when I try to use your github url instead of the old one and I can't use the old one either since it doesn't exist. Thanks!

**Comment by slashmo** [comment]
Hi @kneekey23, thanks for bringing this up!

I just tagged a `0.1.0` so you should be able to [install it via Swift PM](https://github.com/slashmo/swift-app-store-receipt-validation/tree/main#usage) now.

**Comment by slashmo** [comment]
> Gives me a version error when I try to use your github url instead of the old one and I can't use the old one either since it doesn't exist
> @kneekey23

Btw., another possibility to fix such an issue would be to load the package from a branch, like this:

```swift
.package(url: "https://github.com/slashmo/swift-app-store-receipt-validation", .branch("main"))
```

**Comment by kneekey23** [comment]
Awesome tip and thank you so much!
